### ISSUE TITLE
Fuel Consumption Calculation

### ISSUE THREAD

**Issue by RuthMeadowMacLeod** [Flight-Path-Analysis/FlightPathAnalysis#105]
Fuel consumption would be a useful metric for us to use, as it's objectively desirable to minimize. So we would like to find some way to calculate or find data on the fuel consumption of various flights.

**Comment by Andrerg01** [comment]
Putting my thoughts here, could be all wrong:

$$Fuel Consumption=SFC\times Thrust\times Duration$$
Where $SFC$ is the aircraft's specific fuel consumption rate per unit of thrust.
Or course, none of this is constant, so.
$$Fuel Consumption=\int SFC(h)\times T(\vec{r}, \dot{\vec\{r}}, \ddot{\vec{r}})dt$$
I'm assuming here that the efficiency of the plane decreases with height.
The thrust (let's assume Newtons) should be something like:
$$T = m*a + D(h, \vec{v}_p,\vec{v}_w)$$
Where $m$ is the mass of the aircraft
$a$ is the acceleration (can be derived from flight data)
and $D$ would some some kind of drag coefficient dependent on the relative speeds of the plane and the wind ($\vec{v}_p$ and $\vec{v}_w$. Remembering that the plane's speed is such that it'll cause a lift force equal to the weight of the plane. I'm lost now.

**Comment by Andrerg01** [comment]
We can know which aircraft is related to each callsign from [this](https://opensky-network.org/datasets/metadata/).
We'd need now a database of aircraft characteristic values to put in our model.

**Comment by Andrerg01** [comment]
A simple model for drag force is just 
$$D=\frac{1}{2}\cdot C_d\cdot A\cdot ρ(h)\cdot V_a^2$$
Where:
$C_d$ is the drag coefficient between air and the aircraft (explained [here](https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/drag-coefficient/)) and it's easy to find ([here](https://en.wikipedia.org/wiki/Drag_coefficient#:~:text=to%20flow%20(2D)-,Aircraft,-%5Bedit%5D) for example)
$A$ is the wing area of the aircraft (also easy to find [here](https://www.modernairliners.com/boeing-787#:~:text=Feet%2C%203%20Inches)-,Wing,-Area)) 
$V_a$ is the airspeed of the aircraft (retrievable for the data we already have)
$\rho(h)$ is the atmospheric density as a function of altitude, and, for aircraft heights, can be expressed as below (courtesy of [wikipedia](https://en.wikipedia.org/wiki/Density_of_air#Variation_with_altitude:~:text=absolute%20pressure.-,Variation%20with%20altitude,-%5Bedit%5D))
$$\rho(h) = \frac{P_0 M}{R T_0}\left(1 - \frac{L h}{T_0}\right)^\left(\frac{gM}{RL}-1\right)$$
All the values there are specified in the wikipedia article.
​

**Comment by kkdsdesilva** [comment]
I've been thinking about this over the weekend. If we can't find accurate fuel consumption info online, I don't know if estimating fuel consumption is the right way to go, especially since we don't have a way to double check if our estimations are good or not.

Do you think it is okay to assume that the flights always took the most fuel efficient path?

**Comment by Andrerg01** [comment]
That's a fair point, we can come up with whatever models for fuel consumption, but it would be amazing if we could test them. But even so, we don't have to make it accurate at all, as long as it's proportional or wrong by no more than a systematic, it would suffice, right?
Call it a Fuel Consumption Index, rather then actual fuel consumption. We still need to quantity the "inefficiency" of a flight path and correlate that to weather influence of the supposed "best" path that it didn't take, AND, correlate the inefficiency of the flight with the weather on the path that it DID take.
Personally I'd say that having a good enough model is necessary, and having it be systematically inaccurate is not an issue, as it would still reflect trends. 
Any thoughts @RuthMeadowMacLeod @nthom74?

**Comment by kkdsdesilva** [comment]
> Call it a Fuel Consumption Index, rather then actual fuel consumption. We still need to quantify the "inefficiency" of a flight path and correlate that to weather influence of the supposed "best" path that it didn't take, AND, correlate the inefficiency of the flight with the weather influence on the path that it DID take.

@Andrerg01 I agree. But I was thinking it might be easier to quantify the "inefficiency" just by looking at the difference between the distance travelled by the flight and the actual distance between the two airports (assuming the shortest path is the most efficient). Am I missing something?

**Comment by Andrerg01** [comment]
That was the initial thought, yes. We strayed from that idea during the meeting, because of
 - There could be (and there probably are) many different routes that are just as efficient as each other , and the route seems to be highly dependent on which runway the plane departs from as well, which skews what a "best path" means.
<img width="705" alt="image" src="https://github.com/Flight-Path-Analysis/FlightPathAnalysis/assets/29161499/5e7f19d8-663e-4939-8da5-93f3ec34fb4d">
 - Fuel efficiency is a direct metric that's interest to stakeholders, and what we want to minimize in the end anyway.
 - Distance traveled is not the only factor, say the flight is traveling the shortest path, but it's always agains the wind and takes twice as long? Maybe flight duration could be a good substitute there, as in; the shorter the flight, the least fuel it consumed. But if it's short because it went twice as fast, then the drag force would be 4 times as large, and so the fuel consumption would still be larger.

I'm not trying to push away ideas, please if it's the group consensus I'm happy to give in. However I do believe that some fuel consumption model, or some efficiency index of some sort, is the best approach.
We can bring this up again on the next meeting and see what the group thinks, if we don't come to a consensus here.

**Comment by RuthMeadowMacLeod** [comment]
This is what I've been looking into, though Dumindu found something which seems like it will likely work better.

The thrust, $T$ on the airplane at a given time, $t$, is $T(t) = (m_{initital}-m_{FC}(t))(a(t)-g)-\frac{\rho(t)v^2(t)}{2}(c_DA_D+c_\ell A_\ell)$.

- $m_{initial}$ is the mass of the airplane at takeoff, which includes the mass of the plane itself, passengers, baggage, and starting fuel. I think our best bet for this might be to try and pick flights at times/locations that we're pretty sure will be full, and then we can use the number of seats plus average passenger/baggage weight to estimate this value.
- $m_{FC}(t)$ is the mass of fuel that has been consumed so far at time $t$. Ultimately, we want $m_{FC}(t_f)$ where $t_f$ is the time that the flight ends.
- $a(t)$ and $v(t)$ are the acceleration and velocity of the plane, I think relative to the wind. We should be able to use our data and linearly interpolate it to get these functions.
- $g$ is the constant which is approximately $9.807$.
- $\rho(t)$ is the air density at time $t$, which we should be able to get from the altitude data.
- $c_D$ and $C_\ell$ are respectively the coefficients of drag and lift for the airplane. These are determined experimentally, and we may be able to find them for our airplanes. For example, here are the coefficients for the Boeing 787-8 [https://www.lissys.uk/samp1/index.html](https://www.lissys.uk/samp1/index.html.)
- $A_D$ and $A_\ell$ are the corresponding reference areas for the coefficients of drag and lift. It's possible they will be the same area. Hopefully, wherever we find the coefficients, it should also state the corresponding reference area.

Then, if we can find data/tables about the relationship between thrust and specific fuel consumption for our airplane, we should be able to fit it to a function, $f(T)$ which outputs the rate of fuel consumption for a given thrust value. So $\frac{dm_{FC}}{dt}=f(T)$. It will be useful to think of thrust as a function of time, and $m_{FC}$, so we'll get the differential equation: $\frac{d m_{FC}}{dt} = f(T(t, m_{FC}))$. Then it should be possible to solve this for $m_{FC}(t)$ using something like [https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.ode.html](url) or [https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html](url).

**Comment by kkdsdesilva** [comment]
These are all the details I found about the OpenAP library:
https://openap.dev
https://openap.dev/features
https://openap.dev/emission

The external website that compares OpenAP estimations with 'real' data:
https://traffic-viz.github.io/tutorial/fuel_burn.html

I also found this pdf with fuel performance data for different types of aircrafts at different situations. I don't know how helpful it is since we can't use this data without extracting them from the pdf:
https://www.eurocontrol.int/sites/default/files/library/015_BADA_Aircraft_Performance_Summary_Tables.pdf

**Comment by Andrerg01** [comment]
Closed! Creating issue to add it to code
